<?php
return array(
    'category'=>array(
        'title'=>'内容分类',
        'items'=>array(
            'index'=>'内容分类查看',
            'add'=>'内容分类添加',
            'update'=>'内容分类修改',
            'delete'=>'内容分类删除'
        )
    ),
    'post'=>array(
        'title'=>'内容管理',
        'items'=>array(
            'index'=>'文章查看',
            'add'=>'文章添加',
            'update'=>'文章修改',
            'delete'=>'文章删除',
            'push'=>'文章发布'
        )
    ),
    'page'=>array(
        'title'=>'页面管理',
        'items'=>array(
            'index'=>'页面查看',
            'add'=>'页面添加',
            'update'=>'页面修改',
            'delete'=>'页面删除'
        )
    ),
    'notice'=>array(
        'title'=>'公告管理',
        'items'=>array(
            'index'=>'公告查看',
            'add'=>'公告添加',
            'update'=>'公告修改',
            'delete'=>'公告删除'
        )
    ),
    'feedback'=>array(
        'title'=>'留言管理',
        'items'=>array(
            'index'=>'留言查看',
            'reply'=>'留言回复',
            'delete'=>'留言删除'
        )
    ),
    'links'=>array(
        'title'=>'友链管理',
        'items'=>array(
            'index'=>'友链查看',
            'add'=>'友链添加',
            'update'=>'友链修改',
            'delete'=>'友链删除'
        )
    ),
    'member'=>array(
        'title'=>'会员管理',
        'items'=>array(
            'index'=>'会员查看',
            'log'=>'会员日志',
            'logview'=>'会员日志查看',
            'logclear'=>'会员日志清除',
            'add'=>'会员添加',
            'update'=>'会员修改',
            'delete'=>'会员禁用',
            'set_agent'=>'设置代理',
            'cancel_agent'=>'取消代理'
        )
    ),
    'invite'=>array(
        'title'=>'邀请码管理',
        'items'=>array(
            'index'=>'邀请码查看',
            'add'=>'生成邀请码',
            'update'=>'转赠邀请码'
        )
    ),
    'paylog'=>array(
        'title'=>'财务相关',
        'items'=>array(
            'recharge'=>'充值查看',
            'rechargeupdate'=>'充值确认',
            'rechargecancel'=>'充值撤销',
            'rechargedelete'=>'充值删除',
            'cashin'=>'提现查看',
            'cashinupdate'=>'提现处理',
            'cashdelete'=>'提现删除'
        )
    ),
    'manager'=>array(
        'title'=>'管理员管理',
        'items'=>array(
            'index'=>'管理员查看',
            'log'=>'管理员日志',
            'logview'=>'管理员日志查看',
            'logclear'=>'管理员日志清除',
            'add'=>'管理员添加',
            'update'=>'管理员修改',
            'permision'=>'管理员权限',
            'delete'=>'管理员禁用'
        )
    ),
    'setting'=>array(
        'title'=>'系统配置',
        'items'=>array(
            'index'=>'系统配置',
            'advance'=>'配置管理',
            'add'=>'配置添加',
            'update'=>'配置修改',
            'delete'=>'配置删除'
        )
    ),
    'paytype'=>array(
        'title'=>'充值方式',
        'items'=>array(
            'index'=>'充值方式查看',
            'add'=>'充值方式添加',
            'update'=>'充值方式修改',
            'delete'=>'充值方式删除'
        )
    )
);
//end