<?php
return array(
    'category'=>array(
        'title'=>'内容分类',
        'items'=>array(
            'index'=>'分类查看',
            'add'=>'分类添加',
            'edit'=>'分类修改',
            'delete'=>'分类删除'
        )
    ),
    'article'=>array(
        'title'=>'内容管理',
        'items'=>array(
            'index'=>'文章查看',
            'add'=>'文章添加',
            'edit'=>'文章修改',
            'delete'=>'文章删除',
            'status'=>'文章发布',
            'imagelist'=>'文章图集',
            'imageadd'=>'添加图片',
            'imageupdate'=>'修改图片',
            'imagedelete'=>'删除图片',
            'comments'=>'评论查看',
            'commentview'=>'评论回复',
            'commentstatus'=>'评论审核',
            'commentdelete'=>'评论删除'
        )
    ),
    'productcategory'=>array(
        'title'=>'产品分类',
        'items'=>array(
            'index'=>'分类查看',
            'add'=>'分类添加',
            'edit'=>'分类修改',
            'delete'=>'分类删除'
        )
    ),
    'product'=>array(
        'title'=>'产品管理',
        'items'=>array(
            'index'=>'产品查看',
            'add'=>'产品添加',
            'edit'=>'产品修改',
            'delete'=>'产品删除',
            'push'=>'产品上下架',
            'get_specs'=>'规格数据',
            'imagelist'=>'文章图集',
            'imageadd'=>'添加图片',
            'imageupdate'=>'修改图片',
            'imagedelete'=>'删除图片',
            'comments'=>'评论查看',
            'commentview'=>'评论回复',
            'commentstatus'=>'评论审核',
            'commentdelete'=>'评论删除'
        )
    ),
    'productcoupon'=>array(
        'title'=>'优惠券管理',
        'items'=>array(
            'index'=>'优惠券管理',
            'add'=>'添加优惠券',
            'update'=>'修改优惠券',
            'delete'=>'删除优惠券',
            'itemlist'=>'已领优惠券',
            'itemdelete'=>'删除已领优惠券'
        ),
    ),
    'order'=>array(
        'title'=>'订单管理',
        'items'=>array(
            'index'=>'订单列表',
            'export'=>'订单导出',
            'detail'=>'订单详情',
            'delete'=>'订单删除',
            'audit'=>'订单审核',
            'setstatus'=>'状态批量更新',
            'setcancel'=>'取消订单',
            'setpayed'=>'订单支付',
            'setdelivery'=>'订单发货',
            'setreceive'=>'订单收货',
            'setcomplete'=>'订单完成'
        )
    ),
    'page'=>array(
        'title'=>'页面管理',
        'items'=>array(
            'index'=>'页面查看',
            'add'=>'页面添加',
            'edit'=>'页面修改',
            'delete'=>'页面删除'
        )
    ),
    'notice'=>array(
        'title'=>'公告管理',
        'items'=>array(
            'index'=>'公告查看',
            'add'=>'公告添加',
            'edit'=>'公告修改',
            'delete'=>'公告删除'
        )
    ),
    'adv'=>array(
        'title'=>'广告管理',
        'items'=>array(
            'index'=>'广告位置查看',
            'add'=>'广告位置添加',
            'update'=>'广告位置修改',
            'delete'=>'广告位置删除',
            'itemlist'=>'广告查看',
            'itemadd'=>'广告添加',
            'itemupdate'=>'广告修改',
            'itemdelete'=>'广告删除'
        )
    ),
    'feedback'=>array(
        'title'=>'留言管理',
        'items'=>array(
            'index'=>'留言查看',
            'reply'=>'留言回复',
            'delete'=>'留言删除'
        )
    ),
    'links'=>array(
        'title'=>'友链管理',
        'items'=>array(
            'index'=>'友链查看',
            'add'=>'友链添加',
            'edit'=>'友链修改',
            'delete'=>'友链删除'
        )
    ),
    'member'=>array(
        'title'=>'会员管理',
        'items'=>array(
            'index'=>'会员查看',
            'log'=>'会员日志',
            'logview'=>'会员日志查看',
            'logclear'=>'会员日志清除',
            'add'=>'会员添加',
            'update'=>'会员修改',
            'status'=>'会员禁用',
            'delete'=>'会员删除',
            'set_agent'=>'设置代理',
            'cancel_agent'=>'取消代理'
        )
    ),
    'invite'=>array(
        'title'=>'邀请码管理',
        'items'=>array(
            'index'=>'邀请码查看',
            'add'=>'生成邀请码',
            'update'=>'转赠邀请码'
        )
    ),
    'paylog'=>array(
        'title'=>'财务相关',
        'items'=>array(
            'index'=>'第三方支付明细',
            'recharge'=>'充值查看',
            'rechargeupdate'=>'充值确认',
            'rechargecancel'=>'充值撤销',
            'rechargedelete'=>'充值删除',
            'cashin'=>'提现查看',
            'cashinupdate'=>'提现处理',
            'cashdelete'=>'提现删除'
        )
    ),
    'manager'=>array(
        'title'=>'管理员管理',
        'items'=>array(
            'index'=>'管理员查看',
            'log'=>'管理员日志',
            'logview'=>'管理员日志查看',
            'logclear'=>'管理员日志清除',
            'add'=>'管理员添加',
            'update'=>'管理员修改',
            'permision'=>'管理员权限',
            'delete'=>'管理员禁用'
        )
    ),
    'setting'=>array(
        'title'=>'系统配置',
        'items'=>array(
            'index'=>'系统配置查看',
            'update'=>'配置保存',
            'import'=>'配置导入',
            'export'=>'配置导出',
            'advance'=>'配置管理',
            'add'=>'配置添加',
            'edit'=>'配置修改',
            'delete'=>'配置删除'
        )
    ),
    'paytype'=>array(
        'title'=>'充值方式',
        'items'=>array(
            'index'=>'充值方式查看',
            'add'=>'充值方式添加',
            'edit'=>'充值方式修改',
            'delete'=>'充值方式删除'
        )
    ),
    'wechat'=>array(
        'title'=>'微信管理',
        'items'=>array(
            'index'=>'公众号列表',
            'add'=>'公众号添加',
            'edit'=>'公众号修改',
            'delete'=>'公众号删除',
            'uploadVerify'=>'上传验证文件',
            'updateField'=>'公众号配置',
        )
    ),
    'wechat.fans'=>array(
        'title'=>'微信粉丝管理',
        'items'=>array(
            'index'=>'粉丝列表',
            'sendmsg'=>'推送消息',
            'sync'=>'同步粉丝',
        ),
    ),
    'wechat.menu'=>array(
        'title'=>'微信菜单管理',
        'items'=>array(
            'edit'=>'编辑菜单',
        ),
    ),
    'wechat.material'=>array(
        'title'=>'微信素材管理',
        'items'=>array(
            'index'=>'素材列表',
            'sync'=>'素材同步',
            'delete'=>'删除素材',
        ),
    ),
    'wechat.reply'=>array(
        'title'=>'微信回复管理',
        'items'=>array(
            'index'=>'回复列表',
            'add'=>'添加回复',
            'edit'=>'编辑回复',
            'delete'=>'删除回复',
        ),
    ),
    'wechat.tplmsg'=>array(
        'title'=>'微信模板消息设置',
        'items'=>array(
            'index'=>'模板消息查看',
            'sync'=>'同步模板消息',
            'add'=>'添加模板消息',
            'del'=>'删除模板消息',
        ),
    ),
);
//end