#!/usr/bin/php
<?php

// [ 应用入口文件 ]
namespace think;

define('DOC_ROOT',__DIR__.'/public');

require __DIR__ . '/thinkphp/base.php';

ini_set('memory_limit','2048M');

// 支持事先使用静态方法设置Request对象和Config对象

// 执行应用并响应
Container::get('app')->path(__DIR__ . '/application/')->bind('task/Util/daily')->run()->send();