#!/usr/bin/php
<?php

// [ 应用入口文件 ]
namespace think;

define('DOC_ROOT',__DIR__.'/public');

ini_set('memory_limit','2048M');

// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

// 执行应用并响应
$http = (new App())->http;

$response = $http->path(__DIR__ . '/app/')->bind('task/Util/daily')->run();

$response->send();

$http->end($response);